# Generated by Django 2.1.3 on 2018-11-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181120_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
