# Generated by Django 2.1.3 on 2018-11-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20181123_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
    ]
