# Generated by Django 2.1.3 on 2018-11-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_comment_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=250)),
                ('username', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='books.Book')),
            ],
        ),
    ]
