# Generated by Django 2.1.3 on 2018-11-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20181124_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='u0pdated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='u0pdated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='social',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='books.Book'),
        ),
    ]
