# Generated by Django 2.1.3 on 2018-11-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20181124_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='books.Book'),
        ),
    ]
